export const products = [{
        id: 1,
        building: 'Barker Center',
        room: 'Thompson',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'Lav',
        freq_range: '554-590 MHZ',
        freq_band: 'J1',
        group: 'G2',
        channel: 'CH20',
        assigned_frequency: '589.725 MHZ',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['installedMic']
    },
    {
        id: 2,
        building: 'Barker Center',
        room: 'Thompson',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'HandHeld',
        freq_range: '554-590 MHZ',
        freq_band: 'J1',
        group: 'G2',
        channel: 'CH19',
        assigned_frequency: '589.725 MHZ',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['portableMic', 'roamingMic']

    },
    {
        id: 3,
        building: 'Barker Center',
        room: 'Thompson',
        make: 'Shure',
        model: 'Axient Digital',
        mic_type: 'LAV',
        freq_range: '470- 616 MHZ',
        freq_band: 'G57',
        group: 'G5',
        channel: 'CH243',
        assigned_frequency: '602.350 MHZ',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['portableMic', 'roamingMic']
    },
    {
        id: 4,
        building: 'Barker Center',
        room: 'Thompson',
        make: 'Shure',
        model: 'Axient Digital',
        mic_type: 'HandHeld',
        freq_range: '470- 616 MHZ',
        freq_band: 'G57',
        group: 'G5',
        channel: 'CH245',
        assigned_frequency: '603.700 MHZ',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['portableMic', 'roamingMic']
    },
    {
        id: 5,
        building: 'Barker Center',
        room: 'Thompson',
        make: 'Shure',
        model: 'Axient Digital',
        mic_type: 'HandHeld',
        freq_range: '470- 616 MHZ',
        freq_band: 'G57',
        group: 'G5',
        channel: 'CH247',
        assigned_frequency: '604.850 MHz',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['portableMic', 'roamingMic']
    },
    {
        id: 6,
        building: 'Barker Center',
        room: 'Thompson',
        make: 'Shure',
        model: 'Axient Digital',
        mic_type: 'HandHeld',
        freq_range: '470- 616 MHZ',
        freq_band: 'G57',
        group: 'G5',
        channel: 'CH249',
        assigned_frequency: '605.875 MHz',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['portableMic', 'roamingMic']
    },
    {
        id: 7,
        building: 'BioLab',
        room: 'Lecture H 1080',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'LAV',
        freq_range: '554.590MHZ',
        freq_band: 'J1',
        group: 'G2',
        channel: 'CH16',
        assigned_frequency: '584.375MHZ',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['portableMic', 'roamingMic']
    },
    {
        id: 8,
        building: 'BioLab',
        room: 'Lecture H 1080',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'HandHeld',
        freq_range: '554.590MHZ',
        freq_band: 'J1',
        group: 'G2',
        channel: 'CH11',
        assigned_frequency: '578.075MHZ',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['installedMic']
    },
    {
        id: 9,
        building: 'Boylston Hall',
        room: 'Fong Auditorium',
        make: 'Shure',
        model: 'ULX S4',
        mic_type: 'Lav',
        freq_range: '555 - 590 MHZ',
        freq_band: 'J1',
        group: 'G2',
        channel: 'Ch20',
        assigned_frequency: '589.725 MHz',
        serial_number: '0928071325-01',
        comments: ' Boujour Vue.js',
        categories: ['roamingMic']
    },
    {
        id: 10,
        building: 'Boylston Hall',
        room: 'Fong Auditorium',
        make: 'Shure',
        model: 'QLX-D',
        mic_type: 'HandHeld',
        freq_range: '470 - 536 MHZ',
        freq_band: 'G50',
        group: 'G2',
        channel: 'CH66',
        assigned_frequency: '533.450 MHZ',
        serial_number: '417132395395A2092111',
        comments: ' Boujour Vue.js',
        categories: ['portableMic', 'roamingMic']
    },
    {
        id: 11,
        building: 'Boylston Hall',
        room: 'Fong Auditorium',
        make: 'Shure',
        model: 'QLX-D',
        mic_type: 'HandHeld',
        freq_range: '470 - 536 MHZ',
        freq_band: 'G50',
        group: 'G2',
        channel: 'CH67',
        assigned_frequency: '533.820 MHZ',
        serial_number: '417132395495A2092111',
        comments: ' Boujour Vue.js',
        categories: ['installedMic']
    },
    {
        id: 12,
        building: 'Boylston Hall',
        room: 'Boylston 104',
        make: 'Shure',
        model: 'ULX-S',
        mic_type: 'Lav',
        freq_range: '555 - 590 MHZ',
        freq_band: 'G3',
        group: 'G5',
        channel: 'CH9',
        assigned_frequency: '',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['portableMic']
    },
    {
        id: 13,
        building: 'Carpenter Center',
        room: 'Theater',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'Lav #1',
        freq_range: '554 - 590 MHZ',
        freq_band: 'J1',
        group: 'G2',
        channel: 'CH17',
        assigned_frequency: '587.500 MHz',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['installedMic']
    },
    {
        id: 14,
        building: 'Carpenter Center',
        room: 'Theater',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'Lav # 2',
        freq_range: '554 - 590 MHZ',
        freq_band: 'J1',
        group: 'G2',
        channel: 'CH18',
        assigned_frequency: '588.375 MHZ',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['portableMic', 'roamingMic']
    },
    {
        id: 15,
        building: 'Carpenter Center',
        room: 'Theater',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'HandHeld # 2',
        freq_range: '554 - 590 MHZ',
        freq_band: 'J1',
        group: 'G2',
        channel: 'CH18',
        assigned_frequency: '588.375 MHz',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['roamingMic']
    },
    {
        id: 16,
        building: 'Carpenter Center',
        room: 'Theater',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'HandHeld # 3',
        freq_range: '554 - 590 MHZ',
        freq_band: 'J1',
        group: 'G2',
        channel: 'CH19',
        assigned_frequency: '588.800 MHz',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['installedMic']
    },
    {
        id: 17,
        building: 'Carpenter Center',
        room: 'B-04',
        make: 'Shure',
        model: 'L4-K',
        mic_type: 'HandHeld',
        freq_range: 'VHF Fixed',
        freq_band: '',
        group: '---------',
        channel: '_______',
        assigned_frequency: '177.000 MHZ',
        serial_number: 'R9328655186',
        comments: ' Boujour Vue.js',
        categories: ['roamingMic']
    },
    {
        id: 18,
        building: 'Carpenter Center',
        room: 'B-04',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'Lav',
        freq_range: '554 - 590 MHZ',
        freq_band: 'J1',
        group: 'G2',
        channel: 'CH20',
        assigned_frequency: '589.725 MHZ',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['roamingMic']
    },
    {
        id: 19,
        building: 'Center For EU Studies',
        room: 'Conference Room',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'Lav',
        freq_range: '554-590 MHZ',
        freq_band: 'J1',
        group: 'G1',
        channel: 'CH1',
        assigned_frequency: '556.375 MHZ',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['portableMic', 'roamingMic']
    },
    {
        id: 20,
        building: 'CGIS North & South',
        room: 'CGIS S010',
        make: 'Shure',
        model: 'ULX P4',
        mic_type: 'Lav',
        freq_range: '662 - 698 MHZ',
        freq_band: 'M1',
        group: 'G1',
        channel: 'CH1',
        assigned_frequency: '663.025 MHz',
        serial_number: '12345',
        comments: ' Boujour Vue.js',
        categories: ['portableMic', 'roamingMic']
    }
]